/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NursingRouteImport } from './routes/nursing'
import { Route as ParamedicalRouteImport } from './routes/paramedical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NursingRoute = NursingRouteImport.update({
  id: '/nursing',
  path: '/nursing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParamedicalRoute = ParamedicalRouteImport.update({
  id: '/paramedical',
  path: '/paramedical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/nursing': typeof NursingRoute
  '/paramedical': typeof ParamedicalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/nursing': typeof NursingRoute
  '/paramedical': typeof ParamedicalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campus': typeof CampusRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/nursing': typeof NursingRoute
  '/paramedical': typeof ParamedicalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/campus' | '/contact' | '/gallery' | '/nursing' | '/paramedical'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campus' | '/contact' | '/gallery' | '/nursing' | '/paramedical'
  id:
    | '__root__'
    | '/'
    | '/campus'
    | '/contact'
    | '/gallery'
    | '/nursing'
    | '/paramedical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampusRoute: typeof CampusRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NursingRoute: typeof NursingRoute
  ParamedicalRoute: typeof ParamedicalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursing': {
      id: '/nursing'
      path: '/nursing'
      fullPath: '/nursing'
      preLoaderRoute: typeof NursingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paramedical': {
      id: '/paramedical'
      path: '/paramedical'
      fullPath: '/paramedical'
      preLoaderRoute: typeof ParamedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampusRoute: CampusRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NursingRoute: NursingRoute,
  ParamedicalRoute: ParamedicalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
